apiVersion: v1
kind: PersistentVolume
metadata:
  name: prompv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/prom1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prompvc
    
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: prompv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafpv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/graf1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafpvc

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: grafpv

