apiVersion: v1
kind: Service
metadata:
  name: promsvc
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  
spec:
  selector: 
    srilabmonitoring: prometheus-server
  type: LoadBalancer  
  ports:
    - port: 9090
      targetPort: 9090
