apiVersion: v1
kind: ConfigMap
metadata:
  name: graf-ds-cm
  namespace: default
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://promsvc.default.svc.cluster.local:9090",
                "version": 1
            }
        ]
    }
